### ISSUE TITLE
Output histogram names contain slashes

### ISSUE THREAD

**Issue by ktht** [HEP-KBFI/TallinnAnalysis#1] opened 2022-07-14 15:26 UTC
Can't even do `.ls` when opening the file in `root`. There should be a directory structure.

**Comment by veelken** [comment] 2022-07-15 07:49
The issue is fixed by this commit:
  https://github.com/HEP-KBFI/TallinnAnalysis/commit/45b7245a06723051e2fdbbab795b5a369d27fe01

**Closed by veelken** 2022-07-15 07:49 UTC
